// Prepopulated region/country lists for the VPN profile form's region
// field (see VPN.jsx). Snapshot data, not live-fetched — PIA_REGIONS from
// PIA's public server list (serverlist.piaservers.net/vpninfo/servers/v6,
// WireGuard-capable regions only), NORDVPN_COUNTRIES from NordVPN's public
// countries list (api.nordvpn.com/v1/servers/countries). Region field stays
// free text either way — these only drive the <datalist> suggestions, so an
// id added by a provider after this snapshot still works if typed manually.

export const PIA_REGIONS = [
  { id: 'ar-so', name: 'AR Streaming Optimized' },
  { id: 'at-so', name: 'AT Streaming Optimized' },
  { id: 'au_adelaide-pf', name: 'AU Adelaide' },
  { id: 'au_brisbane-pf', name: 'AU Brisbane' },
  { id: 'aus_melbourne', name: 'AU Melbourne' },
  { id: 'aus_perth', name: 'AU Perth' },
  { id: 'aus', name: 'AU Sydney' },
  { id: 'al', name: 'Albania' },
  { id: 'dz', name: 'Algeria' },
  { id: 'ad', name: 'Andorra' },
  { id: 'ar', name: 'Argentina' },
  { id: 'yerevan', name: 'Armenia' },
  { id: 'au_australia-so', name: 'Australia Streaming Optimized' },
  { id: 'austria', name: 'Austria' },
  { id: 'br-so', name: 'BR Streaming Optimized' },
  { id: 'bahamas', name: 'Bahamas' },
  { id: 'bangladesh', name: 'Bangladesh' },
  { id: 'belgium', name: 'Belgium' },
  { id: 'bo_bolivia-pf', name: 'Bolivia' },
  { id: 'ba', name: 'Bosnia and Herzegovina' },
  { id: 'br', name: 'Brazil' },
  { id: 'sofia', name: 'Bulgaria' },
  { id: 'ca', name: 'CA Montreal' },
  { id: 'ca_ontario', name: 'CA Ontario' },
  { id: 'ca_ontario-so', name: 'CA Ontario Streaming Optimized' },
  { id: 'ca_toronto', name: 'CA Toronto' },
  { id: 'ca_vancouver', name: 'CA Vancouver' },
  { id: 'cl-so', name: 'CL Streaming Optimized' },
  { id: 'cambodia', name: 'Cambodia' },
  { id: 'santiago', name: 'Chile' },
  { id: 'china', name: 'China' },
  { id: 'bogota', name: 'Colombia' },
  { id: 'sanjose', name: 'Costa Rica' },
  { id: 'zagreb', name: 'Croatia' },
  { id: 'cyprus', name: 'Cyprus' },
  { id: 'czech', name: 'Czech Republic' },
  { id: 'de_berlin', name: 'DE Berlin' },
  { id: 'de-frankfurt', name: 'DE Frankfurt' },
  { id: 'de_germany-so', name: 'DE Germany Streaming Optimized' },
  { id: 'denmark', name: 'Denmark' },
  { id: 'spain', name: 'ES Madrid' },
  { id: 'es-so', name: 'ES Streaming Optimized' },
  { id: 'es-valencia', name: 'ES Valencia' },
  { id: 'ec_ecuador-pf', name: 'Ecuador' },
  { id: 'egypt', name: 'Egypt' },
  { id: 'ee', name: 'Estonia' },
  { id: 'fi', name: 'FI Helsinki' },
  { id: 'fi_2', name: 'FI Streaming Optimized' },
  { id: 'fr-so', name: 'FR Streaming Optimized' },
  { id: 'france', name: 'France' },
  { id: 'georgia', name: 'Georgia' },
  { id: 'gr', name: 'Greece' },
  { id: 'greenland', name: 'Greenland' },
  { id: 'gt_guatemala-pf', name: 'Guatemala' },
  { id: 'hk', name: 'Hong Kong' },
  { id: 'il_israel_2-pf', name: 'IL Israel 2' },
  { id: 'il-so', name: 'IL Streaming Optimized' },
  { id: 'italy', name: 'IT Milano' },
  { id: 'italy_2', name: 'IT Streaming Optimized' },
  { id: 'is', name: 'Iceland' },
  { id: 'in', name: 'India' },
  { id: 'jakarta', name: 'Indonesia' },
  { id: 'man', name: 'Isle of Man' },
  { id: 'israel', name: 'Israel' },
  { id: 'japan_2', name: 'JP Streaming Optimized' },
  { id: 'japan', name: 'JP Tokyo' },
  { id: 'kr-so', name: 'KR Streaming Optimized' },
  { id: 'kazakhstan', name: 'Kazakhstan' },
  { id: 'lt-so', name: 'LT Streaming Optimized' },
  { id: 'lu-so', name: 'LU Streaming Optimized' },
  { id: 'lv', name: 'Latvia' },
  { id: 'liechtenstein', name: 'Liechtenstein' },
  { id: 'lt', name: 'Lithuania' },
  { id: 'lu', name: 'Luxembourg' },
  { id: 'mx-so', name: 'MX Streaming Optimized' },
  { id: 'macau', name: 'Macao' },
  { id: 'malta', name: 'Malta' },
  { id: 'mexico', name: 'Mexico' },
  { id: 'md', name: 'Moldova' },
  { id: 'monaco', name: 'Monaco' },
  { id: 'mongolia', name: 'Mongolia' },
  { id: 'montenegro', name: 'Montenegro' },
  { id: 'morocco', name: 'Morocco' },
  { id: 'nl_netherlands-so', name: 'NL Netherlands Streaming Optimized' },
  { id: 'nz-so', name: 'NZ Streaming Optimized' },
  { id: 'np_nepal-pf', name: 'Nepal' },
  { id: 'nl_amsterdam', name: 'Netherlands' },
  { id: 'nz', name: 'New Zealand' },
  { id: 'nigeria', name: 'Nigeria' },
  { id: 'mk', name: 'North Macedonia' },
  { id: 'no', name: 'Norway' },
  { id: 'pl-so', name: 'PL Streaming Optimized' },
  { id: 'pt-so', name: 'PT Streaming Optimized' },
  { id: 'panama', name: 'Panama' },
  { id: 'pe_peru-pf', name: 'Peru' },
  { id: 'philippines', name: 'Philippines' },
  { id: 'poland', name: 'Poland' },
  { id: 'pt', name: 'Portugal' },
  { id: 'qatar', name: 'Qatar' },
  { id: 'ro-so', name: 'RO Streaming Optimized' },
  { id: 'rs-so', name: 'RS Streaming Optimized' },
  { id: 'ro', name: 'Romania' },
  { id: 'sweden', name: 'SE Stockholm' },
  { id: 'sweden_2', name: 'SE Streaming Optimized' },
  { id: 'sg-so', name: 'SG Streaming Optimized' },
  { id: 'sk-so', name: 'SK Streaming Optimized' },
  { id: 'saudiarabia', name: 'Saudi Arabia' },
  { id: 'rs', name: 'Serbia' },
  { id: 'sg', name: 'Singapore' },
  { id: 'sk', name: 'Slovakia' },
  { id: 'slovenia', name: 'Slovenia' },
  { id: 'za', name: 'South Africa' },
  { id: 'kr_south_korea-pf', name: 'South Korea' },
  { id: 'srilanka', name: 'Sri Lanka' },
  { id: 'tw-so', name: 'TW Streaming Optimized' },
  { id: 'taiwan', name: 'Taiwan' },
  { id: 'tr', name: 'Turkey' },
  { id: 'uk', name: 'UK London' },
  { id: 'uk_southampton', name: 'UK Southampton' },
  { id: 'uk_2', name: 'UK Streaming Optimized' },
  { id: 'us_alabama-pf', name: 'US Alabama' },
  { id: 'us_alaska-pf', name: 'US Alaska' },
  { id: 'us_arkansas-pf', name: 'US Arkansas' },
  { id: 'us_atlanta', name: 'US Atlanta' },
  { id: 'us-baltimore', name: 'US Baltimore' },
  { id: 'us_california', name: 'US California' },
  { id: 'us_chicago', name: 'US Chicago' },
  { id: 'us_connecticut-pf', name: 'US Connecticut' },
  { id: 'us_denver', name: 'US Denver' },
  { id: 'us-newjersey', name: 'US East' },
  { id: 'us-streaming', name: 'US East Streaming Optimized' },
  { id: 'us_florida', name: 'US Florida' },
  { id: 'us-honolulu', name: 'US Honolulu' },
  { id: 'us_houston', name: 'US Houston' },
  { id: 'us_idaho-pf', name: 'US Idaho' },
  { id: 'us-indiana', name: 'US Indiana' },
  { id: 'us_iowa-pf', name: 'US Iowa' },
  { id: 'us_kansas-pf', name: 'US Kansas' },
  { id: 'us-kentucky', name: 'US Kentucky' },
  { id: 'us_las_vegas', name: 'US Las Vegas' },
  { id: 'us_louisiana-pf', name: 'US Louisiana' },
  { id: 'us_maine-pf', name: 'US Maine' },
  { id: 'us_minnesota-pf', name: 'US Minnesota' },
  { id: 'us_mississippi-pf', name: 'US Mississippi' },
  { id: 'us_missouri-pf', name: 'US Missouri' },
  { id: 'us_montana-pf', name: 'US Montana' },
  { id: 'us_nebraska-pf', name: 'US Nebraska' },
  { id: 'us_new_hampshire-pf', name: 'US New Hampshire' },
  { id: 'us_new_mexico-pf', name: 'US New Mexico' },
  { id: 'us_new_york_city', name: 'US New York' },
  { id: 'us_north_carolina-pf', name: 'US North Carolina' },
  { id: 'us_north_dakota-pf', name: 'US North Dakota' },
  { id: 'us_oklahoma-pf', name: 'US Oklahoma' },
  { id: 'us_oregon-pf', name: 'US Oregon' },
  { id: 'us_pennsylvania-pf', name: 'US Pennsylvania' },
  { id: 'us-salt-lake-city', name: 'US Salt Lake City' },
  { id: 'us_seattle', name: 'US Seattle' },
  { id: 'us_silicon_valley', name: 'US Silicon Valley' },
  { id: 'us_south_carolina-pf', name: 'US South Carolina' },
  { id: 'us_south_dakota-pf', name: 'US South Dakota' },
  { id: 'us-tennessee', name: 'US Tennessee' },
  { id: 'us_south_west', name: 'US Texas' },
  { id: 'us_vermont-pf', name: 'US Vermont' },
  { id: 'us_washington_dc', name: 'US Washington DC' },
  { id: 'us3', name: 'US West' },
  { id: 'us-streaming-2', name: 'US West Streaming Optimized' },
  { id: 'us_west_virginia-pf', name: 'US West Virginia' },
  { id: 'us-wilmington', name: 'US Wilmington' },
  { id: 'us_wisconsin-pf', name: 'US Wisconsin' },
  { id: 'us_wyoming-pf', name: 'US Wyoming' },
  { id: 'ua', name: 'Ukraine' },
  { id: 'ae', name: 'United Arab Emirates' },
  { id: 'uy_uruguay-pf', name: 'Uruguay' },
  { id: 'venezuela', name: 'Venezuela' },
  { id: 'vietnam', name: 'Vietnam' },
  { id: 'za-so', name: 'ZA Streaming Optimized' },
]

export const NORDVPN_COUNTRIES = [
  { code: 'af', name: 'Afghanistan' },
  { code: 'al', name: 'Albania' },
  { code: 'dz', name: 'Algeria' },
  { code: 'ad', name: 'Andorra' },
  { code: 'ao', name: 'Angola' },
  { code: 'ag', name: 'Antigua and Barbuda' },
  { code: 'ar', name: 'Argentina' },
  { code: 'am', name: 'Armenia' },
  { code: 'au', name: 'Australia' },
  { code: 'at', name: 'Austria' },
  { code: 'az', name: 'Azerbaijan' },
  { code: 'bs', name: 'Bahamas' },
  { code: 'bh', name: 'Bahrain' },
  { code: 'bd', name: 'Bangladesh' },
  { code: 'bb', name: 'Barbados' },
  { code: 'be', name: 'Belgium' },
  { code: 'bz', name: 'Belize' },
  { code: 'bj', name: 'Benin' },
  { code: 'bm', name: 'Bermuda' },
  { code: 'bt', name: 'Bhutan' },
  { code: 'bo', name: 'Bolivia' },
  { code: 'ba', name: 'Bosnia and Herzegovina' },
  { code: 'bw', name: 'Botswana' },
  { code: 'br', name: 'Brazil' },
  { code: 'bn', name: 'Brunei Darussalam' },
  { code: 'bg', name: 'Bulgaria' },
  { code: 'bf', name: 'Burkina Faso' },
  { code: 'kh', name: 'Cambodia' },
  { code: 'ca', name: 'Canada' },
  { code: 'cv', name: 'Cape Verde' },
  { code: 'ky', name: 'Cayman Islands' },
  { code: 'td', name: 'Chad' },
  { code: 'cl', name: 'Chile' },
  { code: 'co', name: 'Colombia' },
  { code: 'km', name: 'Comoros' },
  { code: 'cr', name: 'Costa Rica' },
  { code: 'hr', name: 'Croatia' },
  { code: 'cy', name: 'Cyprus' },
  { code: 'cz', name: 'Czech Republic' },
  { code: 'dk', name: 'Denmark' },
  { code: 'do', name: 'Dominican Republic' },
  { code: 'ec', name: 'Ecuador' },
  { code: 'eg', name: 'Egypt' },
  { code: 'sv', name: 'El Salvador' },
  { code: 'ee', name: 'Estonia' },
  { code: 'et', name: 'Ethiopia' },
  { code: 'fj', name: 'Fiji' },
  { code: 'fi', name: 'Finland' },
  { code: 'fr', name: 'France' },
  { code: 'gm', name: 'Gambia' },
  { code: 'ge', name: 'Georgia' },
  { code: 'de', name: 'Germany' },
  { code: 'gh', name: 'Ghana' },
  { code: 'gr', name: 'Greece' },
  { code: 'gl', name: 'Greenland' },
  { code: 'gu', name: 'Guam' },
  { code: 'gt', name: 'Guatemala' },
  { code: 'gy', name: 'Guyana' },
  { code: 'hn', name: 'Honduras' },
  { code: 'hk', name: 'Hong Kong' },
  { code: 'hu', name: 'Hungary' },
  { code: 'is', name: 'Iceland' },
  { code: 'in', name: 'India' },
  { code: 'id', name: 'Indonesia' },
  { code: 'iq', name: 'Iraq' },
  { code: 'ie', name: 'Ireland' },
  { code: 'im', name: 'Isle of Man' },
  { code: 'il', name: 'Israel' },
  { code: 'it', name: 'Italy' },
  { code: 'jm', name: 'Jamaica' },
  { code: 'jp', name: 'Japan' },
  { code: 'je', name: 'Jersey' },
  { code: 'jo', name: 'Jordan' },
  { code: 'kz', name: 'Kazakhstan' },
  { code: 'ke', name: 'Kenya' },
  { code: 'kw', name: 'Kuwait' },
  { code: 'kg', name: 'Kyrgyzstan' },
  { code: 'la', name: "Lao People's Democratic Republic" },
  { code: 'lv', name: 'Latvia' },
  { code: 'lb', name: 'Lebanon' },
  { code: 'lr', name: 'Liberia' },
  { code: 'ly', name: 'Libyan Arab Jamahiriya' },
  { code: 'li', name: 'Liechtenstein' },
  { code: 'lt', name: 'Lithuania' },
  { code: 'lu', name: 'Luxembourg' },
  { code: 'mg', name: 'Madagascar' },
  { code: 'mw', name: 'Malawi' },
  { code: 'my', name: 'Malaysia' },
  { code: 'mv', name: 'Maldives' },
  { code: 'mt', name: 'Malta' },
  { code: 'mr', name: 'Mauritania' },
  { code: 'mu', name: 'Mauritius' },
  { code: 'mx', name: 'Mexico' },
  { code: 'md', name: 'Moldova' },
  { code: 'mc', name: 'Monaco' },
  { code: 'mn', name: 'Mongolia' },
  { code: 'me', name: 'Montenegro' },
  { code: 'ma', name: 'Morocco' },
  { code: 'mz', name: 'Mozambique' },
  { code: 'mm', name: 'Myanmar' },
  { code: 'np', name: 'Nepal' },
  { code: 'nl', name: 'Netherlands' },
  { code: 'nz', name: 'New Zealand' },
  { code: 'ng', name: 'Nigeria' },
  { code: 'mk', name: 'North Macedonia' },
  { code: 'no', name: 'Norway' },
  { code: 'pk', name: 'Pakistan' },
  { code: 'pa', name: 'Panama' },
  { code: 'pg', name: 'Papua New Guinea' },
  { code: 'py', name: 'Paraguay' },
  { code: 'pe', name: 'Peru' },
  { code: 'ph', name: 'Philippines' },
  { code: 'pl', name: 'Poland' },
  { code: 'pt', name: 'Portugal' },
  { code: 'pr', name: 'Puerto Rico' },
  { code: 'qa', name: 'Qatar' },
  { code: 'ro', name: 'Romania' },
  { code: 'lc', name: 'Saint Lucia' },
  { code: 'sn', name: 'Senegal' },
  { code: 'rs', name: 'Serbia' },
  { code: 'sc', name: 'Seychelles' },
  { code: 'sl', name: 'Sierra Leone' },
  { code: 'sg', name: 'Singapore' },
  { code: 'sk', name: 'Slovakia' },
  { code: 'si', name: 'Slovenia' },
  { code: 'so', name: 'Somalia' },
  { code: 'za', name: 'South Africa' },
  { code: 'kr', name: 'South Korea' },
  { code: 'es', name: 'Spain' },
  { code: 'lk', name: 'Sri Lanka' },
  { code: 'sr', name: 'Suriname' },
  { code: 'se', name: 'Sweden' },
  { code: 'ch', name: 'Switzerland' },
  { code: 'tw', name: 'Taiwan' },
  { code: 'tj', name: 'Tajikistan' },
  { code: 'tz', name: 'Tanzania' },
  { code: 'th', name: 'Thailand' },
  { code: 'tt', name: 'Trinidad and Tobago' },
  { code: 'tn', name: 'Tunisia' },
  { code: 'tr', name: 'Turkey' },
  { code: 'ua', name: 'Ukraine' },
  { code: 'ae', name: 'United Arab Emirates' },
  { code: 'gb', name: 'United Kingdom' },
  { code: 'us', name: 'United States' },
  { code: 'uy', name: 'Uruguay' },
  { code: 'uz', name: 'Uzbekistan' },
  { code: 've', name: 'Venezuela' },
  { code: 'vn', name: 'Vietnam' },
  { code: 'ye', name: 'Yemen' },
  { code: 'zm', name: 'Zambia' },
]
